name: HelloWorld
main: com.ender.HelloWorld
version: 1.0
api-version: 1.16
# YAML 中的注释，一行有效
# 以上是插件基本信息，以下是命令注册
commands:
  enderwhitelist: # 命令的基本名，请不要使用奇怪的字符！
    aliases: # 别名，方便玩家使用
      - "ew"
    usage: "/enderwhitelist <movement> <player-name>" # 用法
    description: "用于管理离线服务器的白名单" # 描述
    permission: "minecraft.command.whitelist" # 需要的权限，通常不用
    permission-message: "Only an OP have permissions to do this." # 无权限返回的消息，通常不用